Build/config/routes.rb
Todoit::Application.routes.draw do
  resources :users
  resources :user_sessions, only: [:new , :create]

  

  

  resources :todoit_lists do
    resources :todoit_items do
      member do
        patch :complete
      end 
    end 
  end 
  root 'todoit_lists#index'

end

Build/app/models/todoit_item.rb
class TodoitItem < ActiveRecord::Base
  belongs_to :todoit_list

  validates :content, presence: true,
                          length: { minimum: 2} 


  scope :complete, -> { where("completed_at is not null") }
  scope :incomplete, -> { where(completed_at: nil) }


  def completed?
    !completed_at.blank?
  end 





end

Build/app/models/todoit_list.rb
class TodoitList < ActiveRecord::Base

    has_many :todoit_items 



    validates :title, presence: true 
    validates :title, length: { minimum: 3}
    validates :description, presence: true
    validates :description, length: { minimum: 5}
    validates :text, presence: true
    validates :text, length: { minimum: 5}

    def has_completed_items?
      todoit_items.completed.size > 0 
    end 

    def has_incomplete_items?
      todoit_items.incomplete.size > 0
    end

end

Build/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true,
                    uniqueness: true,
                    format: {
                      with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
                    }

  before_save :downcase_email

  def downcase_email
    self.email = email.downcase
  end
end

Build/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :success


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    if current_user
      true
    else
      redirect_to new_user_session_path, notice: "You must login to access your todolist contact marcus for support"
  end
end

Build/app/controllers/todoit_items_controller.rb
class TodoitItemsController < ApplicationController
  
  before_action :find_todoit_list

  def index

  end

  def new
    
    @todoit_item = @todoit_list.todoit_items.new 
  end 


  def create
    
    @todoit_item = @todoit_list.todoit_items.new(todoit_item_params)
    if @todoit_item.save
      flash[:success] = "Added todoit list item."
      redirect_to todoit_list_todoit_items_path
    else
      flash[:error] = "There was a problem adding that todoit list item."
      render action: :new
    end
  end

  def edit

  end 

  def update
      @todoit_list = TodoitList.find(params[:todoit_list_id])
      @todoit_item = @todoit_list.todoit_items.find(params[:id])
      if @todoit_item.update_attributes(todoit_item_params) 
        flash[:success] = "Saved a todoit list item again!"
        redirect_to todoit_list_todoit_items_path
      else
        flash[:error] = "That todoit item couldn't be saved "
        render action: :edit
      end
  end 

  def destroy 
    @todoit_item = @todoit_list.todoit_items.find(params[:id])
    if @todoit_item.destroy
      flash[:success] = "Todoit list item was deleted"
    else 
      flash[:error] = "Todoit list was not deleted"
    end

    redirect_to todoit_list_todoit_items_path

  end 

  def complete
    @todoit_item = @todoit_list.todoit_items.find(params[:id])
    @todoit_item.update_attribute(:completed_at, Time.now)
    redirect_to todoit_list_todoit_items_path, notice: "Todoit item is marked as completed"
  end

  def url_options
    { todoit_list_id: params[:todoit_list_id] }.merge(super)
  end

  private 
  def find_todoit_list
    @todoit_list = TodoitList.find(params[:todoit_list_id])
  end 

  private
  def todoit_item_params
    params[:todoit_item].permit(:content)
  end



end

Build/app/controllers/todoit_lists_controller.rb
class TodoitListsController < ApplicationController
  before_action :set_todoit_list, only: [:show, :edit, :update, :destroy]

  # GET /todoit_lists
  # GET /todoit_lists.json
  def index
    @todoit_lists = TodoitList.all
  end

  # GET /todoit_lists/1
  # GET /todoit_lists/1.json
  def show
  end

  # GET /todoit_lists/new
  def new
    @todoit_list = TodoitList.new
  end

  # GET /todoit_lists/1/edit
  def edit
  end

  # POST /todoit_lists
  # POST /todoit_lists.json
  def create
    @todoit_list = TodoitList.new(todoit_list_params)

    respond_to do |format|
      if @todoit_list.save
        format.html { redirect_to @todoit_list, notice: 'Todoit list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todoit_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @todoit_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todoit_lists/1
  # PATCH/PUT /todoit_lists/1.json
  def update
    respond_to do |format|
      if @todoit_list.update(todoit_list_params)
        format.html { redirect_to @todoit_list, notice: 'Todoit list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todoit_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todoit_lists/1
  # DELETE /todoit_lists/1.json
  def destroy
    @todoit_list.destroy
    respond_to do |format|
      format.html { redirect_to todoit_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todoit_list
      @todoit_list = TodoitList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todoit_list_params
      params.require(:todoit_list).permit(:title, :description, :text)
    end
end

Build/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to todo_lists_path

  else
    flash[:error] = "There was a problem logging into your ToDo account. Please check your password and e-mail otherwise contact Marcus!"
    render action: 'new'
    
    end   
  end
end

Build/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json

  def create
    @user = User.new(user_params)
 
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to todo_lists_path, success: 'Thanks for signing up!' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

Build/app/helpers/application_helper.rb
module ApplicationHelper
end

Build/app/helpers/todoit_items_helper.rb
module TodoitItemsHelper
end

Build/app/helpers/todoit_lists_helper.rb
module TodoitListsHelper
end

Build/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

Build/app/helpers/users_helper.rb
module UsersHelper
end

Build/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todoit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="nav">
    <h1><%= link_to "ToDoIt", root_path %> </h1>
    <ul>

        <li><%= link_to "Sign Up", new_user_path %> </li>
          
      </ul>
      <br class="clear" />
  </div>


  

  <% flash.each do |type, message| %>
  <div class="alert flash <%= type %>">
    <%= message %>

  </div>
  <%end %>

<%= yield %>

</body>
</html>

Build/app/views/todoit_items/_form.html.erb
<% if @todoit_item.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@todoit_item.errors.count, "error") %> prohibited this todo item from being saved:</h2>

  <ul>
    <% @todoit_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<%= form.label :content %>
<%= form.text_field :content %>
<br> <p>
<%= form.submit "Save Item", class: 'button_item' %>

Build/app/views/todoit_items/edit.html.erb
<h1><%= @todoit_list.title %> - Editing Todo List Item</h1>
<%= form_for [@todoit_list, @todoit_item] do |form| %>
  <%= render partial: form %>
<% end %>

Build/app/views/todoit_items/index.html.erb
<h1><%= @todoit_list.title %></h1>

<table class="todoit_items">
  <% @todoit_list.todoit_items.each do |todoit_item| %>
  <tr id="<%= dom_id(todoit_item) %>">
    <td>
      <% if todoit_item.completed? %>
      <%= todoit_item.completed_at %>
    <% else %>
      <%= link_to "Mark as Complete", complete_todoit_list_todoit_item_path(todoit_item),
        method: :patch %>
    <% end %>
    </td>
    <td><%= todoit_item.content %></td>
    <td>
    <%= link_to "Edit", edit_todoit_list_todoit_item_path(todoit_item) %>
    <%= link_to "Delete", todoit_list_todoit_item_path(todoit_item), method: :delete, data: { confirm: "Are you sure?" } %>
  </td>
  <% end %>
</tr>

<p class="newtodolist">
  <%= link_to "New ToDoIt Item", new_todoit_list_todoit_item_path %>
</p>

Build/app/views/todoit_items/new.html.erb
<h1> <%= @todoit_list.title %> - Adding the ToDoIt Item </h1>
<%= form_for [@todoit_list, @todoit_item] do |form| %>

  <%= render partial: form %>

<% end %>

Build/app/views/todoit_lists/_form.html.erb
<%= form_for(@todoit_list) do |f| %>
  <% if @todoit_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todoit_list.errors.count, "error") %> prohibited this todoit_list from being saved:</h2>

      <ul>
      <% @todoit_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Build/app/views/todoit_lists/edit.html.erb
<h1>Editing todoit_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @todoit_list %> |
<%= link_to 'Back', todoit_lists_path %>

Build/app/views/todoit_lists/index.html.erb
<h1></h1>
<p><br><br>
<%= link_to 'New Todoit list', new_todoit_list_path , class: 'add_new_list'  %>
<% @todoit_lists.each do |todoit_list| %>
<div class="todoit_list" id="<%= dom_id(todoit_list) %>">
      <tr id="<%= dom_id(todoit_list) %>">
        <h2><%= todoit_list.title %></h2>
        <p><%= todoit_list.description %></p>
        <ul class="functions">
          <li class="list_to" > <%= link_to "List Items", todoit_list_todoit_items_path(todoit_list) %> </li>
          <li class="show_to"> <%= link_to 'Show', todoit_list %></li>
          <li class="edit_to"> <%= link_to 'Edit', edit_todoit_list_path(todoit_list) %></li>
          <li class="delete_to"> <%= link_to 'Destroy', todoit_list, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </ul>
    </div>
<% end %>

<br class="clear">

Build/app/views/todoit_lists/new.html.erb
<h1>New todoit_list</h1>

<%= render 'form' %>

<%= link_to 'Back', todoit_lists_path %>

Build/app/views/todoit_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todoit_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todoit_list.description %>
</p>

<p>
  <strong>Text:</strong>
  <%= @todoit_list.text %>
</p>

<%= link_to 'Edit', edit_todoit_list_path(@todoit_list) %> |
<%= link_to 'Back', todoit_lists_path %>

Build/app/views/user_sessions/new.html.erb
<h1> Log In </h1>
  <%= form_tag user_sessions_path do %>
    <%= label_tag :email, "Email Adddress" %>
    <%= text_field_tag :email, params[:email] %>
    <br />

    <%= label_tag :password, "Password" %>
    <%= password_field_tag :password %>
    <br />

    <%= submit_tag "Log in" %>
  <% end %>

Build/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name, "First Name" %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name, "Last Name" %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
    <div class="field">
    <%= f.label :password_confirmation, "Insert password again"%><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up to make your own todo list" %>
  </div>
<% end %>

Build/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Build/app/views/users/new.html.erb
<h1>Register for ToDoList</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

Build/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>